package cmd

import "testing"

func TestGeneratedHeaderRegex(t *testing.T) {
	cases := map[string]string{
		"# Generated by colorsync — theme: catppuccin-mocha\nrest":  "catppuccin-mocha",
		"# Generated by colorsync - theme: gruvbox-dark":            "gruvbox-dark",
		"# Generated by colorsync   —   theme:   frozen-tundra\nx":  "frozen-tundra",
		"no header here":                                            "",
	}
	for input, want := range cases {
		got := ""
		if m := generatedHeaderRe.FindStringSubmatch(input); len(m) >= 2 {
			got = m[1]
		}
		if got != want {
			t.Errorf("input %q: got %q, want %q", input, got, want)
		}
	}
}

func TestP10kStartMarkerRegex(t *testing.T) {
	cases := map[string]string{
		"# --- colorsync theme start --- theme: catppuccin-mocha\nrest": "catppuccin-mocha",
		"# --- colorsync theme start ---   theme:   gruvbox-dark":       "gruvbox-dark",
		"# --- colorsync theme start ---":                               "", // old format, no name
		"unrelated content":                                             "",
	}
	for input, want := range cases {
		got := ""
		if m := p10kStartMarkerRe.FindStringSubmatch(input); len(m) >= 2 {
			got = m[1]
		}
		if got != want {
			t.Errorf("input %q: got %q, want %q", input, got, want)
		}
	}
}

func TestAstrouiColorschemeRegex(t *testing.T) {
	cases := map[string]string{
		`colorscheme = "frozen-tundra",`: "frozen-tundra",
		`  colorscheme   =   "nord"`:     "nord",
		`-- colorscheme = "ignored"`:     "ignored", // regex isn't comment-aware; documented behavior
		`no colorscheme assignment`:      "",
	}
	for input, want := range cases {
		got := ""
		if m := astrouiColorschemeRe.FindStringSubmatch(input); len(m) >= 2 {
			got = m[1]
		}
		if got != want {
			t.Errorf("input %q: got %q, want %q", input, got, want)
		}
	}
}
