package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/mhdev/dotfiles/tools/colorsync/exporter"
)

func init() {
	Register(Command{
		Name: "current",
		Help: "Show the currently applied theme per target",
		Run:  runCurrent,
	})
}

// generatedHeaderRe matches the "# Generated by colorsync — theme: NAME"
// header written by the tmux and ghostty exporters.
var generatedHeaderRe = regexp.MustCompile(`# Generated by colorsync\s+[—-]\s+theme:\s*(\S+)`)

// astrouiColorschemeRe matches `colorscheme = "NAME"` in astroui.lua.
var astrouiColorschemeRe = regexp.MustCompile(`colorscheme\s*=\s*"([^"]+)"`)

// p10kStartMarkerRe matches the p10k start marker line, capturing the theme
// name when present. Old marker lines without a theme name don't match.
var p10kStartMarkerRe = regexp.MustCompile(`# --- colorsync theme start ---\s+theme:\s*(\S+)`)

func runCurrent(args []string) error {
	rows := []struct {
		target string
		theme  string
		source string
	}{
		{"nvim", currentNvim(), astrouiPath()},
		{"tmux", currentFromHeader(exporter.TmuxDefaultPath()), exporter.TmuxDefaultPath()},
		{"ghostty", currentFromHeader(exporter.GhosttyDefaultPath()), exporter.GhosttyDefaultPath()},
		{"iterm", currentIterm(), itermOutputDir()},
		{"p10k", currentP10k(), exporter.P10kDefaultPath()},
	}

	width := 0
	for _, r := range rows {
		if len(r.target) > width {
			width = len(r.target)
		}
	}

	for _, r := range rows {
		display := r.theme
		if display == "" {
			display = "(none)"
		}
		fmt.Printf("%-*s  %s\n", width+1, r.target+":", display)
	}
	return nil
}

func currentP10k() string {
	data, err := os.ReadFile(exporter.P10kDefaultPath())
	if err != nil {
		return ""
	}
	m := p10kStartMarkerRe.FindSubmatch(data)
	if len(m) >= 2 {
		return string(m[1])
	}
	return ""
}

func astrouiPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "nvim", "lua", "plugins", "astroui.lua")
}

func itermOutputDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "colorsync", "output")
}

func currentNvim() string {
	data, err := os.ReadFile(astrouiPath())
	if err != nil {
		return ""
	}
	m := astrouiColorschemeRe.FindSubmatch(data)
	if len(m) >= 2 {
		return string(m[1])
	}
	return ""
}

func currentFromHeader(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	m := generatedHeaderRe.FindSubmatch(data)
	if len(m) >= 2 {
		return string(m[1])
	}
	return ""
}

// currentIterm reports the most recently written .itermcolors file in the
// output dir, since iTerm's currently-selected profile isn't readable here.
func currentIterm() string {
	entries, err := os.ReadDir(itermOutputDir())
	if err != nil {
		return ""
	}
	type entry struct {
		name string
		mod  int64
	}
	var files []entry
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".itermcolors" {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		files = append(files, entry{e.Name(), info.ModTime().UnixNano()})
	}
	if len(files) == 0 {
		return ""
	}
	sort.Slice(files, func(i, j int) bool { return files[i].mod > files[j].mod })
	return strings.TrimSuffix(files[0].name, ".itermcolors")
}
