-- Auto-generated by colorsync — do not edit
vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end

-- Clear ALL highlight groups (including ones set by previous colorscheme)
for _, group in ipairs(vim.fn.getcompletion('', 'highlight')) do
  vim.api.nvim_set_hl(0, group, {})
end

vim.o.background = 'dark'
vim.g.colors_name = 'frozen_tundra'

local c = {
  bg       = '#0a1020',
  fg       = '#d4e5f7',
  cursor   = '#7ec8e3',
  black    = '#111b2e',
  red      = '#8c4a5a',
  green    = '#5b9ea6',
  yellow   = '#8a9bb2',
  blue     = '#4a7fb5',
  magenta  = '#7a6b9e',
  cyan     = '#5aafcc',
  white    = '#b8cde0',
  br_black   = '#2a3a54',
  br_red     = '#c4707e',
  br_green   = '#7ec8d0',
  br_yellow  = '#adbfda',
  br_blue    = '#6da8e0',
  br_magenta = '#a896c8',
  br_cyan    = '#82d4ef',
  br_white   = '#e8f0fa',
}

local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

-- Editor groups
hi('Normal',        { fg = c.fg, bg = c.bg })
hi('NormalFloat',   { fg = c.fg, bg = c.black })
hi('CursorLine',   { bg = c.black })
hi('CursorColumn', { bg = c.black })
hi('ColorColumn',  { bg = c.black })
hi('LineNr',       { fg = c.br_black })
hi('CursorLineNr', { fg = c.yellow, bold = true })
hi('SignColumn',   { bg = c.bg })
hi('VertSplit',    { fg = c.br_black })
hi('StatusLine',   { fg = c.fg, bg = c.black })
hi('StatusLineNC', { fg = c.br_black, bg = c.black })
hi('Pmenu',        { fg = c.fg, bg = c.black })
hi('PmenuSel',     { fg = c.bg, bg = c.blue })
hi('Visual',       { bg = c.br_black })
hi('Search',       { fg = c.bg, bg = c.yellow })
hi('IncSearch',    { fg = c.bg, bg = c.green })
hi('MatchParen',   { fg = c.yellow, bold = true })
hi('Folded',       { fg = c.br_black, bg = c.black })
hi('NonText',      { fg = c.br_black })

-- Syntax groups
hi('Comment',      { fg = c.br_black, italic = true })
hi('Constant',     { fg = c.yellow })
hi('String',       { fg = c.green })
hi('Character',    { fg = c.green })
hi('Number',       { fg = c.yellow })
hi('Boolean',      { fg = c.yellow })
hi('Float',        { fg = c.yellow })
hi('Identifier',   { fg = c.fg })
hi('Function',     { fg = c.blue })
hi('Statement',    { fg = c.magenta })
hi('Conditional',  { fg = c.magenta })
hi('Repeat',       { fg = c.magenta })
hi('Label',        { fg = c.magenta })
hi('Operator',     { fg = c.cyan })
hi('Keyword',      { fg = c.magenta })
hi('Exception',    { fg = c.red })
hi('PreProc',      { fg = c.cyan })
hi('Include',      { fg = c.magenta })
hi('Define',       { fg = c.magenta })
hi('Type',         { fg = c.cyan })
hi('StorageClass', { fg = c.cyan })
hi('Structure',    { fg = c.cyan })
hi('Special',      { fg = c.magenta })
hi('SpecialChar',  { fg = c.magenta })
hi('Error',        { fg = c.red, bold = true })
hi('Todo',         { fg = c.yellow, bold = true })
hi('Underlined',   { fg = c.blue, underline = true })

-- Diagnostic groups
hi('DiagnosticError', { fg = c.red })
hi('DiagnosticWarn',  { fg = c.yellow })
hi('DiagnosticInfo',  { fg = c.blue })
hi('DiagnosticHint',  { fg = c.cyan })

-- Git diff groups
hi('DiffAdd',    { bg = c.green, fg = c.bg })
hi('DiffChange', { bg = c.yellow, fg = c.bg })
hi('DiffDelete', { bg = c.red, fg = c.bg })
hi('DiffText',   { bg = c.blue, fg = c.bg })

-- Treesitter groups
hi('@variable',          { fg = c.fg })
hi('@function',          { fg = c.blue })
hi('@function.call',     { fg = c.blue })
hi('@method',            { fg = c.blue })
hi('@keyword',           { fg = c.magenta })
hi('@string',            { fg = c.green })
hi('@comment',           { fg = c.br_black, italic = true })
hi('@type',              { fg = c.cyan })
hi('@property',          { fg = c.fg })
hi('@parameter',         { fg = c.fg })
hi('@punctuation',       { fg = c.fg })
hi('@tag',               { fg = c.red })
hi('@tag.attribute',     { fg = c.yellow })
hi('@tag.delimiter',     { fg = c.br_black })
hi('@constructor',       { fg = c.cyan })
hi('@constant.builtin',  { fg = c.yellow })
