package exporter

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mhdev/dotfiles/tools/colorsync/palette"
)

// ExportGhostty writes a Ghostty-format theme include file (key=value pairs)
// for the given theme. The file is meant to be referenced from the main
// ~/.config/ghostty/config via `config-file = ?theme.conf`.
func ExportGhostty(theme *palette.Theme, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# Generated by colorsync — theme: %s\n", theme.Name)
	fmt.Fprintln(f, "# Do not edit manually; changes will be overwritten.")
	fmt.Fprintln(f)

	for i := 0; i < 16; i++ {
		fmt.Fprintf(f, "palette = %d=%s\n", i, theme.Colors[i])
	}
	fmt.Fprintf(f, "background = %s\n", theme.Background)
	fmt.Fprintf(f, "foreground = %s\n", theme.Foreground)
	fmt.Fprintf(f, "cursor-color = %s\n", theme.Cursor)
	fmt.Fprintf(f, "cursor-text = %s\n", theme.Background)
	fmt.Fprintf(f, "selection-background = %s\n", theme.Colors[8])
	fmt.Fprintf(f, "selection-foreground = %s\n", theme.Foreground)

	return nil
}

// WriteGhosttyEscapes emits OSC escape sequences so a running Ghostty
// session updates colors immediately, without a config reload. Wraps in
// tmux pass-through when $TMUX is set.
//
// References:
//   OSC 4  — palette index n
//   OSC 10 — foreground
//   OSC 11 — background
//   OSC 12 — cursor
func WriteGhosttyEscapes(w io.Writer, theme *palette.Theme) {
	inTmux := os.Getenv("TMUX") != ""

	writeOSC := func(body string) {
		if inTmux {
			fmt.Fprintf(w, "\033Ptmux;\033\033]%s\007\033\\", body)
		} else {
			fmt.Fprintf(w, "\033]%s\007", body)
		}
	}

	for i := 0; i < 16; i++ {
		writeOSC(fmt.Sprintf("4;%d;%s", i, toXtermColor(theme.Colors[i])))
	}
	writeOSC("10;" + toXtermColor(theme.Foreground))
	writeOSC("11;" + toXtermColor(theme.Background))
	writeOSC("12;" + toXtermColor(theme.Cursor))
}

// toXtermColor formats a #rrggbb hex string as the rgb:RR/GG/BB form
// expected by xterm-style OSC color sequences.
func toXtermColor(hex string) string {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) != 6 {
		return hex
	}
	return fmt.Sprintf("rgb:%s/%s/%s", hex[0:2], hex[2:4], hex[4:6])
}

// GhosttyDefaultPath returns the path of the include file that the main
// Ghostty config sources via `config-file = ?theme.conf`.
func GhosttyDefaultPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "ghostty", "theme.conf")
}
