package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/mhdev/dotfiles/tools/colorsync/palette"
)

const neovimTemplate = `-- Auto-generated by colorsync — do not edit
vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then vim.cmd('syntax reset') end

-- Clear ALL highlight groups (including ones set by previous colorscheme)
for _, group in ipairs(vim.fn.getcompletion('', 'highlight')) do
  vim.api.nvim_set_hl(0, group, {})
end

vim.o.background = '{{.Background}}'
vim.g.colors_name = '{{.ColorsName}}'

local c = {
  bg       = '{{.Theme.Background}}',
  fg       = '{{.Theme.Foreground}}',
  cursor   = '{{.Theme.Cursor}}',
  black    = '{{index .Theme.Colors 0}}',
  red      = '{{index .Theme.Colors 1}}',
  green    = '{{index .Theme.Colors 2}}',
  yellow   = '{{index .Theme.Colors 3}}',
  blue     = '{{index .Theme.Colors 4}}',
  magenta  = '{{index .Theme.Colors 5}}',
  cyan     = '{{index .Theme.Colors 6}}',
  white    = '{{index .Theme.Colors 7}}',
  br_black   = '{{index .Theme.Colors 8}}',
  br_red     = '{{index .Theme.Colors 9}}',
  br_green   = '{{index .Theme.Colors 10}}',
  br_yellow  = '{{index .Theme.Colors 11}}',
  br_blue    = '{{index .Theme.Colors 12}}',
  br_magenta = '{{index .Theme.Colors 13}}',
  br_cyan    = '{{index .Theme.Colors 14}}',
  br_white   = '{{index .Theme.Colors 15}}',
}

local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

-- Editor groups
hi('Normal',        { fg = c.fg, bg = c.bg })
hi('NormalFloat',   { fg = c.fg, bg = c.black })
hi('CursorLine',   { bg = c.black })
hi('CursorColumn', { bg = c.black })
hi('ColorColumn',  { bg = c.black })
hi('LineNr',       { fg = c.br_black })
hi('CursorLineNr', { fg = c.yellow, bold = true })
hi('SignColumn',   { bg = c.bg })
hi('VertSplit',    { fg = c.br_black })
hi('StatusLine',   { fg = c.fg, bg = c.black })
hi('StatusLineNC', { fg = c.br_black, bg = c.black })
hi('Pmenu',        { fg = c.fg, bg = c.black })
hi('PmenuSel',     { fg = c.bg, bg = c.blue })
hi('Visual',       { bg = c.br_black })
hi('Search',       { fg = c.bg, bg = c.yellow })
hi('IncSearch',    { fg = c.bg, bg = c.green })
hi('MatchParen',   { fg = c.yellow, bold = true })
hi('Folded',       { fg = c.br_black, bg = c.black })
hi('NonText',      { fg = c.br_black })

-- Syntax groups
hi('Comment',      { fg = c.br_black, italic = true })
hi('Constant',     { fg = c.yellow })
hi('String',       { fg = c.green })
hi('Character',    { fg = c.green })
hi('Number',       { fg = c.yellow })
hi('Boolean',      { fg = c.yellow })
hi('Float',        { fg = c.yellow })
hi('Identifier',   { fg = c.fg })
hi('Function',     { fg = c.blue })
hi('Statement',    { fg = c.magenta })
hi('Conditional',  { fg = c.magenta })
hi('Repeat',       { fg = c.magenta })
hi('Label',        { fg = c.magenta })
hi('Operator',     { fg = c.cyan })
hi('Keyword',      { fg = c.magenta })
hi('Exception',    { fg = c.red })
hi('PreProc',      { fg = c.cyan })
hi('Include',      { fg = c.magenta })
hi('Define',       { fg = c.magenta })
hi('Type',         { fg = c.cyan })
hi('StorageClass', { fg = c.cyan })
hi('Structure',    { fg = c.cyan })
hi('Special',      { fg = c.magenta })
hi('SpecialChar',  { fg = c.magenta })
hi('Error',        { fg = c.red, bold = true })
hi('Todo',         { fg = c.yellow, bold = true })
hi('Underlined',   { fg = c.blue, underline = true })

-- Diagnostic groups
hi('DiagnosticError', { fg = c.red })
hi('DiagnosticWarn',  { fg = c.yellow })
hi('DiagnosticInfo',  { fg = c.blue })
hi('DiagnosticHint',  { fg = c.cyan })

-- Git diff groups
hi('DiffAdd',    { bg = c.green, fg = c.bg })
hi('DiffChange', { bg = c.yellow, fg = c.bg })
hi('DiffDelete', { bg = c.red, fg = c.bg })
hi('DiffText',   { bg = c.blue, fg = c.bg })

-- Treesitter groups
hi('@variable',          { fg = c.fg })
hi('@function',          { fg = c.blue })
hi('@function.call',     { fg = c.blue })
hi('@method',            { fg = c.blue })
hi('@keyword',           { fg = c.magenta })
hi('@string',            { fg = c.green })
hi('@comment',           { fg = c.br_black, italic = true })
hi('@type',              { fg = c.cyan })
hi('@property',          { fg = c.fg })
hi('@parameter',         { fg = c.fg })
hi('@punctuation',       { fg = c.fg })
hi('@tag',               { fg = c.red })
hi('@tag.attribute',     { fg = c.yellow })
hi('@tag.delimiter',     { fg = c.br_black })
hi('@constructor',       { fg = c.cyan })
hi('@constant.builtin',  { fg = c.yellow })
`

type neovimData struct {
	Theme      *palette.Theme
	ColorsName string
	Background string
}

func isDark(hex string) bool {
	r, g, b, err := palette.ParseHex(hex)
	if err != nil {
		return true
	}
	// Relative luminance approximation
	lum := 0.299*float64(r) + 0.587*float64(g) + 0.114*float64(b)
	return lum < 128
}

// ExportNeovim writes a Neovim Lua colorscheme file for the given theme.
func ExportNeovim(theme *palette.Theme, path string) error {
	tmpl, err := template.New("neovim").Parse(neovimTemplate)
	if err != nil {
		return fmt.Errorf("parsing neovim template: %w", err)
	}

	bg := "dark"
	if !isDark(theme.Background) {
		bg = "light"
	}

	data := neovimData{
		Theme:      theme,
		ColorsName: strings.ReplaceAll(theme.Name, "-", "_"),
		Background: bg,
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating file: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("executing neovim template: %w", err)
	}

	return nil
}

// NeovimDefaultPath returns the default path for a Neovim colorscheme file.
func NeovimDefaultPath(themeName string) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "nvim", "colors", themeName+".lua")
}

// FormatNeovimActivation returns the Lua command to activate the colorscheme.
func FormatNeovimActivation(themeName string) string {
	name := strings.ReplaceAll(themeName, "-", "_")
	return fmt.Sprintf("vim.cmd('colorscheme %s')", name)
}
