package exporter

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/mhdev/dotfiles/tools/colorsync/palette"
)

// ExportTmux generates a tmux theme.conf file from the given theme.
func ExportTmux(theme *palette.Theme, path string) error {
	bg := theme.Background
	fg := theme.Foreground
	accent := theme.Colors[4]  // blue
	black := theme.Colors[0]   // black
	brBlack := theme.Colors[8] // bright black
	white := theme.Colors[7]   // white

	_ = fg    // available for future use
	_ = white // available for future use

	content := fmt.Sprintf(`# Generated by colorsync — theme: %s
# Do not edit manually; changes will be overwritten.

# Basic status bar
set -g status-style "fg=%s,bg=%s"

# Left side of status bar
set -g status-left-style "fg=%s,bg=%s"
set -g status-left-length 40
set -g status-left "#[fg=%s,bg=%s,bold] #S #[fg=%s,bg=%s,nobold]#[fg=%s,bg=%s] #(whoami) #[fg=%s,bg=%s]#[fg=%s,bg=%s] #I:#P #[fg=%s,bg=%s,nobold]"

# Right side of status bar
set -g status-right-style "fg=%s,bg=%s"
set -g status-right-length 150
set -g status-right "#[fg=%s,bg=%s]#[fg=%s,bg=%s] %%H:%%M:%%S #[fg=%s,bg=%s]#[fg=%s,bg=%s] %%d/%%B/%%Y #[fg=%s,bg=%s]#[fg=%s,bg=%s,bold] #H "

# Window status
set -g window-status-format "  #I:#W#F  "
set -g window-status-current-format "#[fg=%s,bg=%s]#[fg=%s,nobold] #I:#W#F #[fg=%s,bg=%s,nobold]"

# Current window status
set -g window-status-style "fg=%s,bg=%s"

# Window with activity status
set -g window-status-activity-style "fg=%s,bg=%s"

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify centre

# Pane border
set -g pane-border-style "fg=%s,bg=default"

# Active pane border
set -g pane-active-border-style "fg=%s,bg=default"

# Pane number indicator
set -g display-panes-colour %s
set -g display-panes-active-colour %s

# Clock mode
set -g clock-mode-colour %s
set -g clock-mode-style 24

# Message
set -g message-style "fg=%s,bg=%s"

# Command message
set -g message-command-style "fg=%s,bg=%s"

# Mode
set -g mode-style "fg=%s,bg=%s"
`,
		// Header
		theme.Name,
		// status-style
		brBlack, bg,
		// status-left-style
		brBlack, bg,
		// status-left: segment 1 (session name on accent)
		bg, accent, accent, brBlack,
		// status-left: segment 2 (whoami on brBlack)
		bg, brBlack, brBlack, black,
		// status-left: segment 3 (pane index on black)
		brBlack, black, black, bg,
		// status-right-style
		brBlack, bg,
		// status-right: segment 1 (time on black)
		black, bg, brBlack, black,
		// status-right: segment 2 (date on brBlack)
		brBlack, black, bg, brBlack,
		// status-right: segment 3 (host on accent)
		accent, brBlack, bg, accent,
		// window-status-current-format
		bg, black, accent, bg, black,
		// window-status-style
		brBlack, accent,
		// window-status-activity-style
		bg, brBlack,
		// pane-border-style
		brBlack,
		// pane-active-border-style
		accent,
		// display-panes-colour / active
		bg, brBlack,
		// clock-mode-colour
		accent,
		// message-style
		black, accent,
		// message-command-style
		black, bg,
		// mode-style
		bg, accent,
	)

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// TmuxDefaultPath returns the default output path for the tmux theme file.
func TmuxDefaultPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tmux", "theme.conf")
}
